# docker-compose.yml
version: '3.5'

services:

  # Services
  catalog:
    restart: always
    build: ./catalog-service
    depends_on:
      - datastore
    ports:
      - 50051:50051
    environment:
      MICRO_SERVER_ADDRESS: ":50051"
      DB_HOST: "mongodb://datastore:27017"

  cart:
    restart: always
    build: ./cart-service
    depends_on:
      - catalog
    ports:
      - 50052:50051
    environment:
      MICRO_SERVER_ADDRESS: ":50051"
      DB_HOST: "mongodb://datastore:27017"

  user:
    restart: always
    build: ./user-service
    ports:
      - 50053:50051
    environment:
      MICRO_SERVER_ADDRESS: ":50051"
      DB_HOST: "mongodb://datastore:27017"

  # Database tier
  datastore:
    image: mongo
    container_name: datastore
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./data/db:/data/db # ensures data persistence between restarting
    ports:
      - 27017:27017
    command: mongod --logpath=/dev/null

  database:
    image: postgres:alpine
    environment:
      POSTGRES_PASSWORD: "password"
      POSTGRES_USER: "admin"
    ports:
      - 5432:5432