// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/shipping/shipping.proto

package catalog

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/micro/go-micro/v2/api"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for CatalogService service

func NewCatalogServiceEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for CatalogService service

type CatalogService interface {
	CreateAddress(ctx context.Context, in *Address, opts ...client.CallOption) (*CreateAddressResponse, error)
	GetAddresses(ctx context.Context, in *GetRequest, opts ...client.CallOption) (*GetAddressesResponse, error)
	GetAddress(ctx context.Context, in *GetRequest, opts ...client.CallOption) (*Address, error)
	GetCountries(ctx context.Context, in *Request, opts ...client.CallOption) (*GetCountriesResponse, error)
	GetCities(ctx context.Context, in *GetRequest, opts ...client.CallOption) (*GetCitiesResponse, error)
	GetAddAddressData(ctx context.Context, in *Request, opts ...client.CallOption) (*GetAddAddressDataResponse, error)
}

type catalogService struct {
	c    client.Client
	name string
}

func NewCatalogService(name string, c client.Client) CatalogService {
	return &catalogService{
		c:    c,
		name: name,
	}
}

func (c *catalogService) CreateAddress(ctx context.Context, in *Address, opts ...client.CallOption) (*CreateAddressResponse, error) {
	req := c.c.NewRequest(c.name, "CatalogService.CreateAddress", in)
	out := new(CreateAddressResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catalogService) GetAddresses(ctx context.Context, in *GetRequest, opts ...client.CallOption) (*GetAddressesResponse, error) {
	req := c.c.NewRequest(c.name, "CatalogService.GetAddresses", in)
	out := new(GetAddressesResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catalogService) GetAddress(ctx context.Context, in *GetRequest, opts ...client.CallOption) (*Address, error) {
	req := c.c.NewRequest(c.name, "CatalogService.GetAddress", in)
	out := new(Address)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catalogService) GetCountries(ctx context.Context, in *Request, opts ...client.CallOption) (*GetCountriesResponse, error) {
	req := c.c.NewRequest(c.name, "CatalogService.GetCountries", in)
	out := new(GetCountriesResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catalogService) GetCities(ctx context.Context, in *GetRequest, opts ...client.CallOption) (*GetCitiesResponse, error) {
	req := c.c.NewRequest(c.name, "CatalogService.GetCities", in)
	out := new(GetCitiesResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catalogService) GetAddAddressData(ctx context.Context, in *Request, opts ...client.CallOption) (*GetAddAddressDataResponse, error) {
	req := c.c.NewRequest(c.name, "CatalogService.GetAddAddressData", in)
	out := new(GetAddAddressDataResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for CatalogService service

type CatalogServiceHandler interface {
	CreateAddress(context.Context, *Address, *CreateAddressResponse) error
	GetAddresses(context.Context, *GetRequest, *GetAddressesResponse) error
	GetAddress(context.Context, *GetRequest, *Address) error
	GetCountries(context.Context, *Request, *GetCountriesResponse) error
	GetCities(context.Context, *GetRequest, *GetCitiesResponse) error
	GetAddAddressData(context.Context, *Request, *GetAddAddressDataResponse) error
}

func RegisterCatalogServiceHandler(s server.Server, hdlr CatalogServiceHandler, opts ...server.HandlerOption) error {
	type catalogService interface {
		CreateAddress(ctx context.Context, in *Address, out *CreateAddressResponse) error
		GetAddresses(ctx context.Context, in *GetRequest, out *GetAddressesResponse) error
		GetAddress(ctx context.Context, in *GetRequest, out *Address) error
		GetCountries(ctx context.Context, in *Request, out *GetCountriesResponse) error
		GetCities(ctx context.Context, in *GetRequest, out *GetCitiesResponse) error
		GetAddAddressData(ctx context.Context, in *Request, out *GetAddAddressDataResponse) error
	}
	type CatalogService struct {
		catalogService
	}
	h := &catalogServiceHandler{hdlr}
	return s.Handle(s.NewHandler(&CatalogService{h}, opts...))
}

type catalogServiceHandler struct {
	CatalogServiceHandler
}

func (h *catalogServiceHandler) CreateAddress(ctx context.Context, in *Address, out *CreateAddressResponse) error {
	return h.CatalogServiceHandler.CreateAddress(ctx, in, out)
}

func (h *catalogServiceHandler) GetAddresses(ctx context.Context, in *GetRequest, out *GetAddressesResponse) error {
	return h.CatalogServiceHandler.GetAddresses(ctx, in, out)
}

func (h *catalogServiceHandler) GetAddress(ctx context.Context, in *GetRequest, out *Address) error {
	return h.CatalogServiceHandler.GetAddress(ctx, in, out)
}

func (h *catalogServiceHandler) GetCountries(ctx context.Context, in *Request, out *GetCountriesResponse) error {
	return h.CatalogServiceHandler.GetCountries(ctx, in, out)
}

func (h *catalogServiceHandler) GetCities(ctx context.Context, in *GetRequest, out *GetCitiesResponse) error {
	return h.CatalogServiceHandler.GetCities(ctx, in, out)
}

func (h *catalogServiceHandler) GetAddAddressData(ctx context.Context, in *Request, out *GetAddAddressDataResponse) error {
	return h.CatalogServiceHandler.GetAddAddressData(ctx, in, out)
}
